name: gemini_cache
services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "8009:6379"   
      - "8001:8001"
    volumes:
        - redis_data:/data
    restart: unless-stopped
volumes:
    redis_data: