name: gemini_app
services:
  api:
    build: .
    command: python serve.py
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis-stack
    
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "8009:6379"   
      - "8001:8001"
    volumes:
        - redis_data:/data
    restart: unless-stopped
volumes:
    redis_data: